# This configuration file is used by Travis CI to build/test TECA.

language: c

os:
  - linux
#  - osx

sudo: required

dist: trusty # Ubuntu 14.04.

# Build/test only on the master branch.
branches:
  only:
    - master
    - stable

compiler:
  - gcc

install: travis_wait 60 ./.travis/install-$TRAVIS_OS_NAME-deps.sh

env:
  global:
    - ALQUIMIA_DIR=$PWD
    - THIRD_PARTY_LIB_DIR=$HOME
    - CRUNCHTOPE_DIR=$THIRD_PARTY_LIB_DIR/crunchtope-dev
    - PETSC_DIR=$THIRD_PARTY_LIB_DIR/petsc
    - PFLOTRAN_DIR=$THIRD_PARTY_LIB_DIR/pflotran
  jobs:
  - BUILD_TYPE=Debug PETSC_ARCH=petsc_debug DEBUG=1
  - BUILD_TYPE=Release PETSC_ARCH=petsc_opt DEBUG=0

script: 
  - ./.travis/install-petsc.sh
  - ./.travis/install-crunchtope.sh
  - ./.travis/install-pflotran.sh
  - ./.travis/install-alquimia.sh

after_failure: 
  - cat $ALQUIMIA_DIR/build/Testing/Temporary/LastTest.log
